### ISSUE TITLE
testing: meteor npm run chimp-<watch | test> fails on first run 

### ISSUE THREAD

**Issue by Oizor** [meteor/guide#385]
Specifics of this issue can be found in the related [issue posted in the chimp repository](https://github.com/xolvio/chimp/issues/338). If it's possible to run `meteor npm` with a different version then node v0.10 I guess it would resolve the problem. Another solution might be to change the guide article changing the `meteor npm` command to `npm` from the chimp related commands.

**Comment by lorensr** [comment]
Thanks @Oizor for reporting! Reproduction below. So does chimp use your global `npm`? In which case we need to tell people how to install or upgrade your global `npm` to v4 or higher?

Test:
```
describe('app loads', function () {
  beforeEach(function () {
    browser.url('http://localhost:3000');
  });

  it('loads @dev', function () {
    assert.isOk(true);
  });
});
```
The error: 
```
[chimp] Running...
Unhandled rejection ReferenceError: Symbol is not defined
    at Object.applyPrototype (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/wdio-sync/build/index.js:387:71)
    at /usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/wdio-sync/build/index.js:338:52
    at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```
Repro:
``` 
> meteor create chimp-symbol
> meteor add practicalmeteor:mocha
> # add above test file
> chimp --ddp=http://localhost:3000 --watch --mocha --path=tests
```
https://github.com/lorensr/chimp-symbol

**Comment by lorensr** [comment]
I installed node 6 from 

https://nodejs.org/en/download/current/

and now `npm run chimp-watch` runs. Although weirdly it says `assert.isOk is not a function`. Dunno what that's about. 

`meteor npm run chimp-watch` has the same Symbol error though.

@tmeasday Should we tell people to install v6 thusly before doing `npm run chimp-watch`?

**Comment by tmeasday** [comment]
Yeah, we should probably just add a note saying something like "Chimp requires node version 4 or above. For now, the best way to use that is to install node on your machine and `npm run chimp-watch`."

**Comment by tmeasday** [comment]
Thanks @lorensr
